name: t_paris
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_bloc: ^8.1.2
  retrofit: ^4.0.1
  auto_route: ^5.0.4
  get_it: ^7.2.0
  awesome_dio_interceptor: ^1.0.0
  flutter_svg: ^2.0.4
  google_maps_flutter: ^2.2.5
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^6.0.0+1
  auto_route_generator: ^5.0.3
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  #fonts:
  #  - family: GrandParis
    #    fonts:
    #      - asset: assets/fonts/GrandParis-Regular.ttf
    #      - asset: assets/fonts/GrandParis-Italic.ttf
  #        style: italic

  assets:
    - assets/geo/lines.geojson
    - assets/json/lines.json
    - assets/json/stops.json
    - assets/icons/on_cancel.svg
    - assets/icons/on_late.svg
    - assets/icons/on_time.svg
    - assets/icons/symbole_bus.svg
    - assets/icons/symbole_metro.svg
    - assets/icons/symbole_RER.svg
    - assets/icons/symbole_train.svg
    - assets/icons/symbole_tram.svg
    - assets/icons/rer/RER_A_couleur_RVB.svg
    - assets/icons/rer/RER_B_couleur_RVB.svg
    - assets/icons/rer/RER_C_couleur_RVB.svg
    - assets/icons/rer/RER_D_couleur_RVB.svg
    - assets/icons/rer/RER_E_couleur_RVB.svg
    - assets/icons/train/train_H_couleur_RVB.svg
    - assets/icons/train/train_J_couleur_RVB.svg
    - assets/icons/train/train_K_couleur_RVB.svg
    - assets/icons/train/train_L_couleur_RVB.svg
    - assets/icons/train/train_N_couleur_RVB.svg
    - assets/icons/train/train_P_couleur_RVB.svg
    - assets/icons/train/train_R_couleur_RVB.svg
    - assets/icons/train/train_U_couleur_RVB.svg
    - assets/icons/tram/tram_T1_carto_RVB.svg
    - assets/icons/tram/tram_T2_carto_RVB.svg
    - assets/icons/tram/tram_T3a_carto_RVB.svg
    - assets/icons/tram/tram_T3b_carto_RVB.svg
    - assets/icons/tram/tram_T4_carto_RVB.svg
    - assets/icons/tram/tram_T5_carto_RVB.svg
    - assets/icons/tram/tram_T6_carto_RVB.svg
    - assets/icons/tram/tram_T7_carto_RVB.svg
    - assets/icons/tram/tram_T8_carto_RVB.svg
    - assets/icons/tram/tram_T9_carto_RVB.svg
    - assets/icons/tram/tram_T10_carto_RVB.svg
    - assets/icons/tram/tram_T11_carto_RVB.svg
    - assets/icons/tram/tram_T12_carto_RVB.svg
    - assets/icons/tram/tram_T13_carto_RVB.svg
    - assets/icons/metro/metro_1_couleur_RVB.svg
    - assets/icons/metro/metro_2_couleur_RVB.svg
    - assets/icons/metro/metro_3_couleur_RVB.svg
    - assets/icons/metro/metro_4_couleur_RVB.svg
    - assets/icons/metro/metro_5_couleur_RVB.svg
    - assets/icons/metro/metro_6_couleur_RVB.svg
    - assets/icons/metro/metro_7_couleur_RVB.svg
    - assets/icons/metro/metro_8_couleur_RVB.svg
    - assets/icons/metro/metro_9_couleur_RVB.svg
    - assets/icons/metro/metro_10_couleur_RVB.svg
    - assets/icons/metro/metro_11_couleur_RVB.svg
    - assets/icons/metro/metro_12_couleur_RVB.svg
    - assets/icons/metro/metro_13_couleur_RVB.svg
    - assets/icons/metro/metro_14_couleur_RVB.svg
    - assets/icons/metro/metro_15_couleur_RVB.svg
    - assets/icons/metro/metro_16_couleur_RVB.svg
    - assets/icons/metro/metro_17_couleur_RVB.svg
    - assets/icons/metro/metro_18_couleur_RVB.svg